<?php
/**
 * Created by PhpStorm.
 * User: mfw
 * Date: 15/4/10
 * Time: 下午7:22
 */
include_once KOD_DIR_NAME."/smarty/libs/Smarty.class.php";
final class kod_web_smarty_internal_template extends Smarty_Internal_Template{
	public function _subTemplateRender($template, $cache_id, $compile_id, $caching, $cache_lifetime, $data, $scope,
									   $forceTplCache, $uid = null, $content_func = null)
	{
		preg_match('/file:(.*)\.mod\.tpl/',$template,$match);
		if(file_exists(webDIR.$match[1].'.mod.php')){
			include_once(webDIR.$match[1].'.mod.php');
			$className = 'kodMod_'.implode('_',explode('/',$match[1]));
			$modController = new $className();
			$modController->init($data);
		}
		parent::_subTemplateRender($template, $cache_id, $compile_id, $caching, $cache_lifetime, $data, $scope, $forceTplCache, $uid, $content_func); // TODO: Change the autogenerated stub
		if(file_exists(webDIR.$match[1].'.mod.php')){
			$modController->finish($data);
		}
	}
}
final class kod_web_smarty extends Smarty{
	public $template_class = 'kod_web_smarty_internal_template';
	//对smarty里面include方法加载的tpl文件生成的php编译文件进行加工，再存入硬盘
	public static function compilerIncludeTplHtml($allHtml,$tplFile){
		return '<!--include'.rand(0,19).'-->'.$allHtml;
	}

}?>